const lessonTitle = "你一定听见";

const lessonData = [
    // ===== 第1段 =====
    ["你", "nǐ", "you", "awak"],
    ["听过", "tīng guò", "have you heard", "pernahkah awak dengar"],
    ["蒲公英", "pú gōng yīng", "dandelion", "bunga dandelion"],
    ["梳头", "shū tóu", "combing hair", "menyisir rambut"],
    ["的", "de", "", ""],
    ["声音", "shēng yīn", "sound", "bunyi"],
    ["吗", "ma", "", ""],
    ["？", "", "", ""],
    ["<br>", "", "", ""],
    ["听过", "tīng guò", "have you heard", "pernahkah awak dengar"],
    ["80只", "bā shí zhī", "eighty", "lapan puluh ekor"],
    ["蚂蚁", "mǎ yǐ", "ants", "semut"],
    ["小跑", "xiǎo pǎo", "jogging", "berlari kecil"],
    ["的", "de", "", ""],
    ["声音", "shēng yīn", "sound", "bunyi"],
    ["吗", "ma", "", ""],
    ["？", "", "", ""],
    ["<br>", "", "", ""],
    ["听过", "tīng guò", "have you heard", "pernahkah awak dengar"],
    ["雪花", "xuě huā", "snowflakes", "bunga salji"],
    ["飘落", "piāo luò", "falling", "jatuh"],
    ["的", "de", "", ""],
    ["声音", "shēng yīn", "sound", "bunyi"],
    ["吗", "ma", "", ""],
    ["？", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["如果", "rú guǒ", "If", "Jika"],
    ["你", "nǐ", "you", "awak"],
    ["说", "shuō", "say", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["这", "zhè", "these", "ini"],
    ["都是", "dōu shì", "are all", "semuanya"],
    ["想象", "xiǎng xiàng", "imagination", "khayalan"],
    ["出来的", "chū lái de", "imagined", "yang dibayangkan"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["没听过", "méi tīng guò", "haven't heard", "tidak pernah dengar"],
    ["。”", "", "", ""],
    ["那么", "nà me", "then", "maka"],
    ["，", "", "", ""],
    ["请你", "qǐng nǐ", "please", "silakan"],
    ["换一个", "huàn yī gè", "change to", "tukar kepada"],
    ["说法", "shuō fǎ", "way of saying", "cara berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["没注意", "méi zhù yì", "didn't pay attention", "tidak perasan"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["这", "zhè", "This", "Ini"],
    ["就", "jiù", "then", "maka"],
    ["对了", "duì le", "is right", "betul"],
    ["。", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["没听过", "méi tīng guò", "haven't heard", "tidak pernah dengar"],
    ["，", "", "", ""],
    ["是", "shì", "because", "kerana"],
    ["因为", "yīn wèi", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["没注意", "méi zhù yì", "didn't pay attention", "tidak perasan"],
    ["；", "", "", ""],
    ["如果", "rú guǒ", "If", "Jika"],
    ["你", "nǐ", "you", "awak"],
    ["屏气凝神", "bǐng qì níng shén", "hold your breath and concentrate", "menahan nafas dan menumpukan perhatian"],
    ["，", "", "", ""],
    ["如果", "rú guǒ", "if", "jika"],
    ["你", "nǐ", "you", "awak"],
    ["全神贯注", "quán shén guàn zhù", "concentrate fully", "memberi tumpuan sepenuhnya"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["一定", "yí dìng", "surely", "pasti"],
    ["会听见的", "huì tīng jiàn de", "will hear", "akan mendengar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["当", "dāng", "When", "Apabila"],
    ["你", "nǐ", "you", "awak"],
    ["在", "zài", "in", "pada"],
    ["静夜里", "jìng yè lǐ", "quiet night", "malam yang sunyi"],
    ["，", "", "", ""],
    ["听见", "tīng jiàn", "hear", "mendengar"],
    ["一阵阵", "yī zhèn zhèn", "a series of", "berkali-kali"],
    ["很有节奏", "hěn yǒu jié zòu", "rhythmic", "berirama"],
    ["的", "de", "", ""],
    ["“", "", "", ""],
    ["滴答", "dī dā", "tick-tock", "tik-tok"],
    ["、", "", "", ""],
    ["滴答", "dī dā", "tick-tock", "tik-tok"],
    ["”", "", "", ""],
    ["声", "shēng", "sound", "bunyi"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["一定", "yí dìng", "surely", "pasti"],
    ["知道", "zhī dào", "know", "tahu"],
    ["，", "", "", ""],
    ["那是", "nà shì", "that is", "itu adalah"],
    ["钟表", "zhōng biǎo", "clock", "jam"],
    ["在行走", "zài xíng zǒu", "ticking", "berjalan"],
    ["；", "", "", ""],
    ["当", "dāng", "When", "Apabila"],
    ["你", "nǐ", "you", "awak"],
    ["在", "zài", "in", "pada"],
    ["睡梦中", "shuì mèng zhōng", "in your sleep", "dalam tidur"],
    ["，", "", "", ""],
    ["听到", "tīng dào", "hear", "mendengar"],
    ["由远而近", "yóu yuǎn ér jìn", "from far to near", "dari jauh ke dekat"],
    ["，", "", "", ""],
    ["又", "yòu", "and", "dan"],
    ["由近而远", "yóu jìn ér yuǎn", "from near to far", "dari dekat ke jauh"],
    ["的", "de", "", ""],
    ["“", "", "", ""],
    ["呜——呜——", "wū——wū——", "woo-woo", "woo-woo"],
    ["”", "", "", ""],
    ["声", "shēng", "sound", "bunyi"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["一定", "yí dìng", "surely", "pasti"],
    ["知道", "zhī dào", "know", "tahu"],
    ["，", "", "", ""],
    ["那是", "nà shì", "that is", "itu adalah"],
    ["火车", "huǒ chē", "train", "kereta api"],
    ["在疾驰", "zài jí chí", "speeding", "melaju"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["这些", "zhè xiē", "These", "Bunyi-bunyi ini"],
    ["声音", "shēng yīn", "sounds", "bunyi"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["都", "dōu", "all", "semua"],
    ["听见了", "tīng jiàn le", "have heard", "telah mendengar"],
    ["。", "", "", ""],
    ["因为", "yīn wèi", "Because", "Kerana"],
    ["这些", "zhè xiē", "these", "ini"],
    ["声音", "shēng yīn", "sounds", "bunyi"],
    ["，", "", "", ""],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["和你", "hé nǐ", "with you", "dengan awak"],
    ["建立了", "jiàn lì le", "established", "membentuk"],
    ["“", "", "", ""],
    ["关系", "guān xì", "connection", "hubungan"],
    ["”", "", "", ""],
    ["，", "", "", ""],
    ["在", "zài", "in", "pada"],
    ["你", "nǐ", "your", "awak punya"],
    ["心里", "xīn lǐ", "heart", "hati"],
    ["留下了", "liú xià le", "left", "meninggalkan"],
    ["“", "", "", ""],
    ["印象", "yìn xiàng", "impression", "kesan"],
    ["”", "", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["那么", "nà me", "Then", "Maka"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["一定", "yí dìng", "surely", "pasti"],
    ["也", "yě", "also", "juga"],
    ["听过", "tīng guò", "have heard", "pernah dengar"],
    ["风", "fēng", "wind", "angin"],
    ["的", "de", "", ""],
    ["声音", "shēng yīn", "sound", "bunyi"],
    ["：", "", "", ""],
    ["风儿", "fēng r", "wind", "angin"],
    ["在", "zài", "in", "di"],
    ["树梢", "shù shāo", "treetops", "puncak pokok"],
    ["呢喃", "ní nán", "whisper", "berbisik"],
    ["，", "", "", ""],
    ["风儿", "fēng r", "wind", "angin"],
    ["在", "zài", "in", "di"],
    ["檐前", "yán qián", "in front of the eaves", "di hadapan cucur atap"],
    ["叹息", "tàn xī", "sigh", "mengeluh"],
    ["，", "", "", ""],
    ["风儿", "fēng r", "wind", "angin"],
    ["在", "zài", "on", "di"],
    ["海面上", "hǎi miàn shàng", "on the sea surface", "di permukaan laut"],
    ["咆哮", "páo xiāo", "roar", "mengaum"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    ["你", "nǐ", "you", "awak"],
    ["一定", "yí dìng", "surely", "pasti"],
    ["也", "yě", "also", "juga"],
    ["听过", "tīng guò", "have heard", "pernah dengar"],
    ["水", "shuǐ", "water", "air"],
    ["的", "de", "", ""],
    ["声音", "shēng yīn", "sound", "bunyi"],
    ["：", "", "", ""],
    ["小溪", "xiǎo xī", "stream", "sungai kecil"],
    ["在", "zài", "in", "di"],
    ["石缝中", "shí fèng zhōng", "among rocks", "di celah-celah batu"],
    ["欢笑", "huān xiào", "laugh", "ketawa"],
    ["，", "", "", ""],
    ["大雨", "dà yǔ", "rain", "hujan"],
    ["在", "zài", "on", "di"],
    ["屋顶上", "wū dǐng shàng", "on the roof", "di atas bumbung"],
    ["跳舞", "tiào wǔ", "dance", "menari"],
    ["，", "", "", ""],
    ["洪流", "hóng liú", "torrent", "arus deras"],
    ["在", "zài", "in", "di"],
    ["山谷中", "shān gǔ zhōng", "in the valley", "di lembah"],
    ["怒吼", "nù hǒu", "roar", "mengguruh"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    ["你", "nǐ", "you", "awak"],
    ["一定", "yí dìng", "surely", "pasti"],
    ["也", "yě", "also", "juga"],
    ["听过大自然中", "tīng guò dà zì rán zhōng", "have heard in nature", "pernah dengar dalam alam"],
    ["各种各样", "gè zhǒng gè yàng", "all kinds of", "pelbagai jenis"],
    ["的", "de", "", ""],
    ["声音", "shēng yīn", "sounds", "bunyi"],
    ["：", "", "", ""],
    ["清脆的", "qīng cuì de", "crisp", "nyaring"],
    ["鸟鸣", "niǎo míng", "bird songs", "bunyi burung"],
    ["、", "", "", ""],
    ["欢快的", "huān kuài de", "cheerful", "riang"],
    ["虫奏", "chóng zòu", "insect chirping", "bunyi serangga"],
    ["、", "", "", ""],
    ["甚至", "shèn zhì", "even", "malahan"],
    ["花开", "huā kāi", "flowers blooming", "bunga mekar"],
    ["的", "de", "", ""],
    ["声音", "shēng yīn", "sound", "bunyi"],
    ["，", "", "", ""],
    ["叶落", "yè luò", "leaves falling", "daun gugur"],
    ["的", "de", "", ""],
    ["声音", "shēng yīn", "sound", "bunyi"],
    ["……", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    ["如果", "rú guǒ", "If", "Jika"],
    ["你", "nǐ", "you", "awak"],
    ["听见了", "tīng jiàn le", "hear", "mendengar"],
    ["，", "", "", ""],
    ["你的", "nǐ de", "your", "awak punya"],
    ["心", "xīn", "heart", "hati"],
    ["就会", "jiù huì", "will", "akan"],
    ["变得", "biàn de", "become", "menjadi"],
    ["柔软", "róu ruǎn", "soft", "lembut"],
    ["，", "", "", ""],
    ["你的", "nǐ de", "your", "awak punya"],
    ["生活", "shēng huó", "life", "kehidupan"],
    ["就会", "jiù huì", "will", "akan"],
    ["变得", "biàn de", "become", "menjadi"],
    ["丰富", "fēng fù", "rich", "kaya"],
    ["。", "", "", ""],
    ["因为", "yīn wèi", "Because", "Kerana"],
    ["你", "nǐ", "you", "awak"],
    ["会发现", "huì fā xiàn", "will discover", "akan mendapati"],
    ["，", "", "", ""],
    ["这个", "zhè ge", "this", "ini"],
    ["世界", "shì jiè", "world", "dunia"],
    ["原来", "yuán lái", "actually", "rupanya"],
    ["是", "shì", "is", "ialah"],
    ["这么", "zhè me", "so", "begitu"],
    ["热闹", "rè nào", "lively", "meriah"],
    ["，", "", "", ""],
    ["这么", "zhè me", "so", "begitu"],
    ["有意思", "yǒu yì si", "interesting", "menarik"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    ["可是", "kě shì", "But", "Tetapi"],
    ["，", "", "", ""],
    ["如果", "rú guǒ", "if", "jika"],
    ["你", "nǐ", "you", "awak"],
    ["总是", "zǒng shì", "always", "sentiasa"],
    ["抱怨", "bào yuàn", "complain", "merungut"],
    ["生活乏味", "shēng huó fá wèi", "life is boring", "hidup membosankan"],
    ["，", "", "", ""],
    ["总是", "zǒng shì", "always", "sentiasa"],
    ["觉得", "jué de", "feel", "rasa"],
    ["无聊", "wú liáo", "bored", "bosan"],
    ["，", "", "", ""],
    ["那么", "nà me", "then", "maka"],
    ["，", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["一定是", "yí dìng shì", "must be", "pasti"],
    ["关上了", "guān shàng le", "closed", "menutup"],
    ["你的", "nǐ de", "your", "awak punya"],
    ["耳朵", "ěr duo", "ears", "telinga"],
    ["。", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["一定", "yí dìng", "surely", "pasti"],
    ["没听见", "méi tīng jiàn", "didn't hear", "tidak mendengar"],
    ["，", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["蒲公英", "pú gōng yīng", "dandelion", "bunga dandelion"],
    ["梳头", "shū tóu", "combing hair", "menyisir rambut"],
    ["的", "de", "", ""],
    ["声音", "shēng yīn", "sound", "bunyi"],
    ["，", "", "", ""],
    ["那", "nà", "those", "itu"],
    ["80只", "bā shí zhī", "eighty", "lapan puluh ekor"],
    ["蚂蚁", "mǎ yǐ", "ants", "semut"],
    ["小跑", "xiǎo pǎo", "jogging", "berlari kecil"],
    ["的", "de", "", ""],
    ["声音", "shēng yīn", "sound", "bunyi"],
    ["，", "", "", ""],
    ["那", "nà", "the", "itu"],
    ["雪花", "xuě huā", "snowflakes", "bunga salji"],
    ["飘落", "piāo luò", "falling", "jatuh"],
    ["的", "de", "", ""],
    ["声音", "shēng yīn", "sound", "bunyi"],
    ["……", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    ["从", "cóng", "From", "Dari"],
    ["现在", "xiàn zài", "now", "sekarang"],
    ["起", "qǐ", "on", "mulai"],
    ["，", "", "", ""],
    ["请", "qǐng", "please", "silakan"],
    ["你", "nǐ", "you", "awak"],
    ["打开", "dǎ kāi", "open", "buka"],
    ["你的", "nǐ de", "your", "awak punya"],
    ["耳朵", "ěr duo", "ears", "telinga"],
    ["，", "", "", ""],
    ["用心", "yòng xīn", "with your heart", "dengan hati"],
    ["去听", "qù tīng", "to listen", "untuk mendengar"],
    ["。", "", "", ""],
    ["你", "nǐ", "you", "awak"],
    ["会听见", "huì tīng jiàn", "will hear", "akan mendengar"],
    ["，", "", "", ""],
    ["美妙的", "měi miào de", "wonderful", "indah"],
    ["乐章", "yuè zhāng", "music", "lagu"],
    ["，", "", "", ""],
    ["就在", "jiù zài", "is right", "berada di"],
    ["你的", "nǐ de", "your", "awak punya"],
    ["身边", "shēn biān", "beside you", "sisi awak"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["桂文亚", "guì wén yà", "Gui Wenya", "Gui Wenya"],
    ["《", "", "", ""],
    ["你一定听见", "nǐ yí dìng tīng jiàn", "You Must Have Heard", "Awak Pasti Mendengar"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
